### ISSUE TITLE
Question about dev status

### ISSUE THREAD

**Issue by COLABORATI** [danapsimer/drupal2hugo#3]
is this project actively worked on or do you need a maintainer?

**Comment by danapsimer** [comment]
This is a fork of a bitbucket project: https://bitbucket.org/rickb777/drupal2hugo

I added some basic behavior that I needed and I have not looked at it since.  My fork on bitbucket is here: https://bitbucket.org/bluesoftdev/drupal2hugo

Please feel free to fork but I would send pull requests to the original project by rickb777 at bitbucket.  

My changes were pretty specific to the drupal site I wanted to migrate.

However, it is a good starting point for getting a tool to migrate a large site to hugo.
